# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ApneaSleep' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ApneaSleep
    pod 'GoogleSignIn'
    pod 'Firebase/Auth'
    pod 'Firebase/Analytics'
    pod 'SwiftKeychainWrapper'
    pod 'lottie-ios'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'IQKeyboardManagerSwift'
    pod 'Pastel'
    pod 'paper-onboarding'
    pod 'Loaf'
    pod 'Comets'
end
